# Generated by Django 4.2 on 2026-05-28 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('dashboard', 'Dashboard'), ('personal', 'Gestión de Personal'), ('biometrico', 'Registro Biométrico'), ('historial', 'Asistencia/Historial'), ('reportes', 'Reportes'), ('horarios', 'Horarios'), ('incidencias', 'Incidencias'), ('dispositivos', 'Dispositivos'), ('configuracion', 'Configuración')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_modulos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permisos_modulos',
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
