# Generated by Django 4.2 on 2026-06-04 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_permisomodulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_almuerzo_inicio', models.TimeField(default='12:00')),
                ('hora_almuerzo_fin', models.TimeField(default='13:00')),
                ('tolerancia_almuerzo_min', models.IntegerField(default=10)),
                ('horas_jornada_completa', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('notificar_retrasos', models.BooleanField(default=True)),
                ('notificar_ausencias', models.BooleanField(default=True)),
                ('nombre_institucion', models.CharField(default='UPTAIET', max_length=200)),
                ('sede', models.CharField(default='Sede Rubio', max_length=100)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
    ]
