# Generated by Django 4.2 on 2026-06-15 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_configuracionsistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('expira_en', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tokens_recuperacion',
            },
        ),
        migrations.CreateModel(
            name='PreguntaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_1', models.CharField(choices=[('pais', '¿País que siempre a querido conocer?'), ('ciudad', '¿País o ciudad de nacimiento?'), ('apellido', '¿Segundo apellido de madre o padre?'), ('colegio', 'Nombre de su colegio primario?'), ('libro', 'Nombre de su libro favorito?'), ('pelicula', 'Nombre de su película favorita?'), ('deporte', '¿Cuál es tu deporte favorito?')], max_length=50)),
                ('respuesta_1_hash', models.CharField(max_length=128)),
                ('pregunta_2', models.CharField(choices=[('pais', '¿País que siempre a querido conocer?'), ('ciudad', '¿País o ciudad de nacimiento?'), ('apellido', '¿Segundo apellido de madre o padre?'), ('colegio', 'Nombre de su colegio primario?'), ('libro', 'Nombre de su libro favorito?'), ('pelicula', 'Nombre de su película favorita?'), ('deporte', '¿Cuál es tu deporte favorito?')], max_length=50)),
                ('respuesta_2_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_seguridad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preguntas_seguridad',
            },
        ),
    ]
