# Generated by Django 4.2 on 2026-06-15 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_tokenrecuperacion_preguntaseguridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=128)),
                ('activo', models.BooleanField(default=True)),
                ('intentos', models.IntegerField(default=0)),
                ('bloqueado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin_seguridad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pins_seguridad',
            },
        ),
    ]
