# Generated by Django 4.2 on 2026-05-10 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biometrico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('estado', models.CharField(choices=[('verificado', 'Verificado'), ('fallido', 'Fallido'), ('manual', 'Manual')], default='vereficado', max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score_verificacion', models.IntegerField(default=0)),
                ('es_retardo', models.BooleanField(default=False)),
                ('minutos_retardo', models.IntegerField(default=0)),
                ('horas_trabajadas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biometrico.dispositivobiometrico')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='personal.empleado')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'db_table': 'registros_asistencia',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=200)),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('datos_antes', models.JSONField(blank=True, null=True)),
                ('datos_despues', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de auditoría',
                'verbose_name_plural': 'Logs de aditoría',
                'db_table': 'log_auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AusenciaAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('justificada', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ausencias', to='personal.empleado')),
            ],
            options={
                'verbose_name': 'Ausencia automática',
                'verbose_name_plural': 'Ausencias automáticas',
                'db_table': 'ausencias_automaticas',
            },
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['empleado', 'timestamp'], name='registros_a_emplead_609cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['timestamp'], name='registros_a_timesta_af9283_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['tipo'], name='registros_a_tipo_85c853_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ausenciaautomatica',
            unique_together={('empleado', 'fecha')},
        ),
    ]
