# Generated by Django 4.2 on 2026-05-22 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_rename_departamento_empleado_departamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaFeriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(unique=True)),
                ('obligatorio', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Día feriado',
                'verbose_name_plural': 'Días feriados',
                'db_table': 'dias_feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='PermisoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERMISO', 'Permiso'), ('REPOSO', 'Reposo Médico'), ('VACACIONES', 'Vacaciones'), ('COMISION', 'Comisión'), ('MATERNIDAD', 'Maternidad/Paternidad'), ('DUELO', 'Duelo'), ('CAPACITACION', 'Capacitación')], default='PERMISO', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='permisos_documentos/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('observacion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to='personal.empleado')),
            ],
            options={
                'verbose_name': 'Permiso de empleado',
                'verbose_name_plural': 'Permisos de empleados',
                'db_table': 'permisos_empleados',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
