# Generated by Django 4.2 on 2026-06-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_diaferiado_permisoempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='es_almuerzo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='horas_extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='horas_faltantes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='minutos_antes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='sin_horario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('salida_almuerzo', 'Salida Almuerzo'), ('entrada_almuerzo', 'Entrada Almuerzo')], max_length=20),
        ),
    ]
