# Generated by Django 4.2 on 2026-05-10 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoBiometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(default='ZK9500', max_length=50)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispositivo Biométrico',
                'verbose_name_plural': 'Dispositivos Biométricos',
                'db_table': 'dispositivos_biometricos',
            },
        ),
        migrations.CreateModel(
            name='HuellaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dedo', models.IntegerField(choices=[(1, 'Pulgar derecho'), (2, 'Índice derecho'), (3, 'Medio derecho'), (4, 'Anular derecho'), (5, 'Meñique derecho'), (6, 'Pulgar izquierdo'), (7, 'Índice izquierdo'), (8, 'Medio izquierdo'), (9, 'Anular izquierdo'), (10, 'Meñique izquierdo')])),
                ('template_encriptado', models.BinaryField()),
                ('calidad', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huellas', to='personal.empleado')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huellas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Huella digital',
                'verbose_name_plural': 'Huellas digitales',
                'db_table': 'huellas_digitales',
                'unique_together': {('empleado', 'numero_dedo')},
            },
        ),
    ]
