# Generated by Django 4.2 on 2026-05-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='Departamento',
            new_name='departamento',
        ),
    ]
