# Generated by Django 4.2 on 2026-06-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_rename_departamento_empleado_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(choices=[('docente', 'Docente'), ('obrero', 'Obrero'), ('administrativo', 'Administrativo'), ('vigilante', 'Vigilante')], max_length=20),
        ),
    ]
